Homework 2
========================================================

```{r setup, include = FALSE}
remotes::install_github("rundel/chunktest")
chunktest::init()

library(testthat)
```


### Task 1 - Re-Implementation

Include a brief description of your implementation here

```{r}
fizzbuzz = function(v) {
  UseMethod("fizzbuzz")
}

fizzbuzz.default = function(v) {
  print(v)
}

```

### Task 2 - Re-Validation & Testing

```{testthat good_input}
context("fizzbuzz good inputs")

#fizzbuzz(1)
test_that("Single Integer", {
  expect_output(fizzbuzz(1), "\\[1\\] 1")
})
```

```{r}
fizzbuzz(3)
fizzbuzz(5)
fizzbuzz(15)

fizzbuzz(9:15)
fizzbuzz(15:9)

fizzbuzz(1:12)
```


#### Bad Inputs

```{testthat bad_input}
context("fizzbuzz good inputs")

#fizzbuzz(1)
test_that("Single Negative Integer", {
  expect_error(fizzbuzz(-1))
})
```

```{r errot=TRUE}
fizzbuzz(-1)
fizzbuzz(-3)
fizzbuzz(-5)

fizzbuzz(TRUE)
fizzbuzz(FALSE)

fizzbuzz(Inf)
fizzbuzz(-Inf)
fizzbuzz(NaN)

fizzbuzz("A")
fizzbuzz(1.5)
fizzbuzz(1i)
fizzbuzz(4i)
```